programs:
  sleeper:
    cmd: "sleep 5"
    numprocs: 2
    umask: 022
    workingdir: .
    autostart: true
    exitcodes: [0]
    startretries: 5
    starttime: 1
    autorestart: always
    stopsignal: TERM
    stoptime: 5
    stdout: /tmp/sleeper.stdout
    stderr: /tmp/sleeper.stderr

  counter:
    cmd: "bash -c 'for i in {1..5}; do echo Count $i; sleep 1; done'"
    numprocs: 1
    umask: 022
    workingdir: .
    autostart: true
    exitcodes: [0]
    startretries: 1
    starttime: 1
    autorestart: unexpected
    stopsignal: TERM
    stoptime: 5
    stdout: /tmp/counter.stdout
    stderr: /tmp/counter.stderr

  spam:
    cmd: "yes 'spam' | head -n 20"
    numprocs: 1
    umask: 022
    workingdir: .
    autostart: true
    exitcodes: [0]
    startretries: 1
    starttime: 1
    autorestart: never
    stopsignal: TERM
    stoptime: 5
    stdout: /dev/null
    stderr: /dev/null

  env_test:
    cmd: "echo $TASKMASTER"
    numprocs: 1
    umask: 022
    workingdir: .
    autostart: true
    exitcodes: [0]
    startretries: 1
    starttime: 1
    autorestart: never
    stopsignal: TERM
    stoptime: 5
    stdout: /tmp/env_test.stdout
    stderr: /tmp/env_test.stderr
    env:
      TASKMASTER: "This is taskmaster"

  failing_process:
    cmd: "sh -c 'exit 1'"
    numprocs: 1
    umask: 022
    workingdir: .
    autostart: true
    exitcodes: [0]
    startretries: 3
    starttime: 1
    autorestart: always
    stopsignal: TERM
    stoptime: 5
    stdout: /tmp/failing_process.stdout
    stderr: /tmp/failing_process.stderr
